## Import

In [1]:
from bertopic import BERTopic
import os
import pandas as pd
from sentence_transformers import SentenceTransformer
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer
import csv
from bertopic.vectorizers import ClassTfidfTransformer
from evaluation import evaluate_model

df = pd.read_csv(os.path.join(os.path.dirname(os.getcwd()), "data", "data_advice_fulltext.csv"))
docs = list(df["text"])
classes = list(df["gen"])

In [2]:
# Pre-calculate embeddings
embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2", use_auth_token=False)
embeddings = embedding_model.encode(docs, show_progress_bar=True)

Batches:   0%|          | 0/32 [00:00<?, ?it/s]

In [3]:
from bertopic.representation import KeyBERTInspired
from bertopic.representation import MaximalMarginalRelevance


# The main representation of a topic
main_representation = KeyBERTInspired()

# Additional ways of representing a topic
aspect_model2 = [KeyBERTInspired(top_n_words=30), MaximalMarginalRelevance(diversity=.5)]

# Add all models together to be run in a single `fit`
representation_model = {
   "KeyBERT": main_representation,
   "MMR":  aspect_model2 
}

In [4]:
#from sklearn.cluster import KMeans

run_name = ""

# Hyperparameters

n_neighbors = 15 # 15 -> BEST 30
n_components = 5 # 5 -> BEST 5
#random_state = [0, 1, 37, 42, 73]
random_state = [37]
min_dist = 0.0
min_cluster_size = 15 # 10 -> BEST 10
min_df = 2 # 2 -> BEST 2 BUT 1 GOOD
ngram_range = (1, 3) # (1, 2) -> BEST (1, 2)
top_n_words = 10 # 10 -> BEST 10

# Data saving

data = []

# Setup different models

cluster_model = HDBSCAN(min_cluster_size=min_cluster_size, metric='euclidean', cluster_selection_method='eom', prediction_data=True)
vectorizer_model = CountVectorizer(stop_words="english", min_df=min_df, ngram_range=ngram_range)
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True) # enable by default --> BEST DEFAULT

# Use the representation model in BERTopic on top of the default pipeline
topic_model = BERTopic()
# Train

for seed in random_state:
    umap_model = UMAP(n_neighbors=n_neighbors, n_components=n_components, min_dist=min_dist, metric='cosine', random_state=seed)

    topic_model = BERTopic(

        # Pipeline models
        embedding_model=embedding_model,
        umap_model=umap_model,
        hdbscan_model=cluster_model,
        vectorizer_model=vectorizer_model,
        representation_model=representation_model,

        # Hyperparameters
        top_n_words=top_n_words,
        n_gram_range=ngram_range,
        min_topic_size="auto", #use HDBSCAN
        verbose=True,

        # General parameters
        calculate_probabilities=True,
        language="english"
    )

    topics, probs = topic_model.fit_transform(docs, embeddings)

    # Evaluate model

    scores = evaluate_model(topic_model, docs, topics, embeddings, topk=top_n_words)  
    data.append([seed, scores[0], scores[1], scores[2], scores[3]])

df = pd.DataFrame(data, columns=["seed", "c_v", "c_npmi", "t_D", "S"])
df

2025-02-07 11:14:04,951 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-02-07 11:14:13,725 - BERTopic - Dimensionality - Completed ✓
2025-02-07 11:14:13,725 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-02-07 11:14:13,787 - BERTopic - Cluster - Completed ✓
2025-02-07 11:14:13,790 - BERTopic - Representation - Extracting topics from clusters using representation models.
2025-02-07 11:14:18,794 - BERTopic - Representation - Completed ✓

   seed       c_v    c_npmi       t_D         S
0    37  0.714023  0.022234  0.554545  0.516455

seed	c_v	c_npmi	t_D	S
0	37	0.801231	0.194546	0.538462	0.520185

In [92]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,KeyBERT,MMR,Representative_Docs
0,-1,174,-1_gnome_gnomes_mushrooms_multiplier,"[gnome, gnomes, mushrooms, multiplier, time, r...","[number mushrooms, gnomes, gnome, colors, colo...","[number mushrooms, gnomes, combinations, pink ...",[the game seems to assign a group of gnomes to...
1,0,203,0_gnome_points_gnomes_colour,"[gnome, points, gnomes, colour, hat, brown, co...","[colour gnome, gnomes, gnome, gnome gives, col...","[colour gnome, gnome gives, yellow, scores, ro...",[Be as quick as you can when choosing the gnom...
2,1,153,1_basket_red_yellow_mushrooms,"[basket, red, yellow, mushrooms, gnomes, red b...","[gnomes yellow basket, gnomes red basket, bask...","[gnomes yellow basket, basket gnomes, mushroom...",[There are two different colours of baskets in...
3,2,105,2_mushrooms_gnome_gnomes_colour,"[mushrooms, gnome, gnomes, colour, try, gives,...","[gnome gives mushrooms, gnomes mushrooms, numb...","[gnome gives mushrooms, gnomes mushrooms, numb...",[There's a pattern when it comes to the gnomes...
4,3,97,3_points_blue_colours_pink,"[points, blue, colours, pink, purple, pattern,...","[certain colours, pick colour, colours, colors...","[certain colours, pick colour, pattern game, s...",[It is said that certain colours score higher ...
5,4,81,4_basket_red_baskets_yellow,"[basket, red, baskets, yellow, points, gnomes,...","[gnomes baskets, colour basket, basket colours...","[gnomes baskets, basket colours, baskets red y...",[On the screen you will be presented with two ...
6,5,66,5_mushrooms_colours_mushroom_change,"[mushrooms, colours, mushroom, change, color, ...","[colors mushrooms, colour gives mushrooms, col...","[colors mushrooms, colour gives mushrooms, mus...",[There are 4 sets of mushroom people. So you ...
7,6,35,6_hats_hat_tall_short,"[hats, hat, tall, short, better, try, taller, ...","[short hats, longer hats, short yellow hat, ha...","[short hats, hat colour, hats pay, yellow hat ...","[Do your best, seems pretty random and difficu..."
8,7,24,7_keys_breaks_fingers_game,"[keys, breaks, fingers, game, make, just, sure...","[stay focused, fingers keys, keys time, focus,...","[stay focused, fingers keys, necessary keys, b...",[You really just have to go with your intuitio...
9,8,24,8_forest_mushrooms_gnomes forest_green,"[forest, mushrooms, gnomes forest, green, gnom...","[mushrooms switch forest, forest number mushro...","[mushrooms switch forest, forest number mushro...","[There are two forests. Green, orange, yellow,..."
10,9,23,9_hat_mushrooms_tall_hats,"[hat, mushrooms, tall, hats, gnome, modifier, ...","[gnomes appear mushrooms, gnome mushrooms, hat...","[gnomes appear mushrooms, gnomes tall hats, la...",[There seems to be no real strategy to this bu...
11,10,15,10_points_mushrooms_gnome_try,"[points, mushrooms, gnome, try, gnomes, colour...","[mushrooms coloured gnome, mushrooms points, g...","[mushrooms coloured gnome, mushrooms points, g...",[The most important thing to remember is not t...

In [93]:
topic_model.visualize_documents(docs)

## Outlier reduction

In [95]:
new_topics_prob = topic_model.reduce_outliers(docs, topics, probabilities=probs, strategy="probabilities")
new_topics_distribution = topic_model.reduce_outliers(docs, topics, strategy="distributions")
new_topics_cTFIDF = topic_model.reduce_outliers(docs, topics, strategy="c-tf-idf", threshold=0.1)
new_topics_embeddings =topic_model.reduce_outliers(docs, topics, strategy="embeddings")
new_topics = {
    "prob": new_topics_prob,
    "distribution": new_topics_distribution,
    "cTFIDF": new_topics_cTFIDF,
    "embeddings": new_topics_embeddings
    }

100%|██████████| 1/1 [00:00<00:00, 13.23it/s]

Test different topic reduction method

In [25]:
for new_topic_name in new_topics:
    topic_model.update_topics(docs, topics=new_topics[new_topic_name])
    print(evaluate_model(topic_model, docs, topics, embeddings, topk=top_n_words))

2025-02-05 18:24:27,917 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

KeyboardInterrupt:

In [96]:
topic_model.update_topics(docs, topics=new_topics["cTFIDF"])
topic_model.get_topic_info()

2025-02-05 19:04:55,509 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

,Topic,Count,Name,Representation,KeyBERT,MMR,Representative_Docs
0,-1,11,-1_the_to_from_combinations,"[the, to, from, combinations, letter, figure o...","[number mushrooms, gnomes, gnome, colors, colo...","[number mushrooms, gnomes, combinations, pink ...",[the game seems to assign a group of gnomes to...
1,0,259,0_the_to_and_gnome,"[the, to, and, gnome, gnomes, you, of, on, it,...","[colour gnome, gnomes, gnome, gnome gives, col...","[colour gnome, gnome gives, yellow, scores, ro...",[Be as quick as you can when choosing the gnom...
2,1,164,1_basket_the_to_red,"[basket, the, to, red, yellow, you, and, mushr...","[gnomes yellow basket, gnomes red basket, bask...","[gnomes yellow basket, basket gnomes, mushroom...",[There are two different colours of baskets in...
3,2,139,2_the_mushrooms_to_of,"[the, mushrooms, to, of, you, gnome, and, gnom...","[gnome gives mushrooms, gnomes mushrooms, numb...","[gnome gives mushrooms, gnomes mushrooms, numb...",[There's a pattern when it comes to the gnomes...
4,3,112,3_the_and_to_it,"[the, and, to, it, points, that, you, blue, fo...","[certain colours, pick colour, colours, colors...","[certain colours, pick colour, pattern game, s...",[It is said that certain colours score higher ...
5,4,83,4_the_basket_to_and,"[the, basket, to, and, red, yellow, gnomes, yo...","[gnomes baskets, colour basket, basket colours...","[gnomes baskets, basket colours, baskets red y...",[On the screen you will be presented with two ...
6,5,79,5_the_mushrooms_to_you,"[the, mushrooms, to, you, and, colours, it, of...","[colors mushrooms, colour gives mushrooms, col...","[colors mushrooms, colour gives mushrooms, mus...",[There are 4 sets of mushroom people. So you ...
7,6,43,6_hats_the_and_hat,"[hats, the, and, hat, to, tall, for, short, yo...","[short hats, longer hats, short yellow hat, ha...","[short hats, hat colour, hats pay, yellow hat ...","[Do your best, seems pretty random and difficu..."
8,7,40,7_the_your_you_to,"[the, your, you, to, and, as, on, it, keys, of]","[stay focused, fingers keys, keys time, focus,...","[stay focused, fingers keys, necessary keys, b...",[You really just have to go with your intuitio...
9,8,27,8_forest_the_to_you,"[forest, the, to, you, other, the other, mushr...","[mushrooms switch forest, forest number mushro...","[mushrooms switch forest, forest number mushro...","[There are two forests. Green, orange, yellow,..."
10,9,26,9_the_hat_mushrooms_of,"[the, hat, mushrooms, of, with, with the, to, ...","[gnomes appear mushrooms, gnome mushrooms, hat...","[gnomes appear mushrooms, gnomes tall hats, la...",[There seems to be no real strategy to this bu...
11,10,17,10_the_points_to_of,"[the, points, to, of, you, mushrooms, most, th...","[mushrooms coloured gnome, mushrooms points, g...","[mushrooms coloured gnome, mushrooms points, g...",[The most important thing to remember is not t...

In [ ]:
topic_model.get_topic(1, full=True)["KeyBERT"]

In [97]:
topic_model.visualize_documents(docs)

In [57]:
topic_model.visualize_hierarchy()

## DATA

Save model

In [4]:
embedding_model = "all-MiniLM-L6-v2"
topic_model.save(os.path.join(os.path.dirname(os.getcwd()), "results", "BERT_fine_tuning", run_name), serialization="safetensors", save_ctfidf=True, save_embedding_model=embedding_model)

Save data

In [5]:
param_str = str({
    "n_neighbors": n_neighbors,
    "n_components": n_components,
    "min_dist": min_dist,
    "random_state": random_state,
    "min_cluster_size": min_cluster_size,
    "min_df": min_df,
    "ngram_range": ngram_range,
    "top_n_words": top_n_words
})


data_run = [[run_name, param_str, df["Diversity"].mean(), df["Coherence"].mean()]]

df_run = pd.DataFrame(data_run, columns=["run_name", "params", "diversity", "coherence"])

df_run.to_csv(os.path.join(os.path.dirname(os.getcwd()), "results", "BERT_fine_tuning", "results.csv"), mode="a", header=False, index=False)

## TEST

In [18]:
from collections import Counter

# Retrieve the vectorizer model
vectorizer = topic_model.vectorizer_model

# Tokenize and count word frequencies
tokens = vectorizer.build_analyzer()(" ".join(docs))  # Tokenize all documents
word_freq = Counter(tokens)  # Count occurrences

# Convert to sorted list
sorted_word_freq = sorted(word_freq.items(), key=lambda x: x[1], reverse=True)

# Print results
print(sorted_word_freq)

[('the', 4856), ('to', 2403), ('and', 1826), ('you', 1581), ('of', 1237), ('gnomes', 987), ('that', 848), ('it', 846), ('mushrooms', 819), ('gnome', 800), ('basket', 787), ('is', 742), ('red', 721), ('yellow', 689), ('with', 599), ('will', 568), ('for', 566), ('in', 560), ('more', 545), ('colour', 544), ('on', 543), ('if', 523), ('are', 483), ('be', 470), ('points', 455), ('as', 453), ('or', 439), ('which', 422), ('blue', 414), ('one', 405), ('to the', 395), ('this', 383), ('brown', 383), ('other', 381), ('so', 381), ('colours', 379), ('purple', 369), ('green', 367), ('but', 367), ('of the', 364), ('when', 361), ('there', 333), ('pink', 330), ('then', 321), ('the other', 311), ('orange', 295), ('try', 290), ('your', 282), ('game', 277), ('out', 273), ('give', 273), ('each', 272), ('have', 263), ('on the', 262), ('time', 261), ('get', 260), ('not', 251), ('at', 249), ('the gnomes', 247), ('of mushrooms', 238), ('was', 237), ('good', 234), ('switch', 226), ('most', 224), ('can', 218), ('choose', 209), ('keep', 207), ('red basket', 207), ('the red', 206), ('different', 205), ('the game', 205), ('than', 199), ('hat', 198), ('best', 196), ('with the', 196), ('they', 194), ('change', 194), ('pick', 187), ('pattern', 186), ('in the', 184), ('the yellow', 180), ('higher', 179), ('the most', 178), ('yellow basket', 178), ('found', 176), ('if you', 173), ('always', 172), ('round', 171), ('more mushrooms', 171), ('color', 170), ('better', 166), ('group', 165), ('gives', 164), ('baskets', 164), ('until', 163), ('to be', 162), ('side', 161), ('think', 160), ('same', 159), ('would', 159), ('rounds', 158), ('number', 156), ('start', 156), ('the gnome', 154), ('luck', 152), ('just', 149), ('the same', 147), ('also', 146), ('two', 145), ('see', 145), ('it is', 145), ('right', 143), ('coloured', 142), ('there are', 142), ('go', 138), ('amount', 138), ('make', 136), ('and the', 135), ('between', 134), ('multiplier', 130), ('high', 129), ('the colour', 128), ('any', 126), ('up', 125), ('don', 125), ('left', 125), ('for the', 125), ('do', 124), ('more points', 124), ('you will', 124), ('hats', 123), ('seemed', 123), ('me', 123), ('from', 123), ('use', 122), ('sure', 122), ('try to', 120), ('take', 119), ('stick', 118), ('number of', 118), ('remember', 114), ('find', 114), ('once', 114), ('you can', 114), ('colors', 113), ('good luck', 113), ('switch to', 112), ('the basket', 112), ('seem', 108), ('colour of', 108), ('over', 107), ('forest', 107), ('my', 106), ('5x', 105), ('select', 105), ('amount of', 104), ('value', 103), ('choosing', 103), ('low', 103), ('of gnomes', 103), ('what', 102), ('may', 102), ('you to', 101), ('the best', 101), ('seems', 100), ('x5', 100), ('that the', 99), ('some', 98), ('mushroom', 98), ('by', 98), ('the colours', 98), ('all', 97), ('score', 96), ('if the', 96), ('after', 95), ('seem to', 95), ('first', 94), ('seemed to', 94), ('x1', 93), ('and blue', 93), ('giving', 91), ('these', 91), ('give you', 91), ('pay', 89), ('sometimes', 89), ('were', 89), ('random', 88), ('advice', 87), ('tall', 86), ('ones', 85), ('work', 84), ('times', 84), ('most mushrooms', 84), ('gave', 83), ('1x', 83), ('when you', 82), ('the number', 82), ('had', 81), ('pair', 81), ('less', 80), ('you get', 80), ('pairs', 79), ('example', 79), ('throughout', 79), ('stick with', 79), ('gnomes are', 79), ('certain', 78), ('like', 78), ('than the', 78), ('notice', 77), ('short', 77), ('choose the', 77), ('attention', 76), ('only', 76), ('and yellow', 76), ('found that', 76), ('purple and', 75), ('yellow orange', 75), ('well', 74), ('them', 74), ('groups', 74), ('and brown', 74), ('there is', 74), ('gnomes that', 74), ('use the', 74), ('few', 73), ('picking', 73), ('too', 73), ('will be', 73), ('and green', 73), ('however', 72), ('orange and', 72), ('make sure', 72), ('for example', 72), ('has', 71), ('red and', 71), ('no', 70), ('while', 70), ('selecting', 70), ('getting', 69), ('either', 69), ('highest', 69), ('gives you', 69), ('the right', 69), ('the left', 69), ('brown and', 69), ('and purple', 68), ('at the', 68), ('blue and', 68), ('and then', 68), ('pink and', 67), ('try and', 67), ('coloured gnomes', 67), ('press', 66), ('you have', 66), ('to get', 66), ('did', 65), ('again', 65), ('changes', 65), ('space', 65), ('when the', 65), ('green and', 65), ('you are', 65), ('yellow and', 64), ('how', 63), ('seems to', 63), ('you the', 63), ('the highest', 63), ('pink purple', 63), ('should', 62), ('gnome with', 62), ('basket and', 62), ('throughout the', 62), ('next', 61), ('breaks', 61), ('that you', 61), ('much', 60), ('based', 60), ('chose', 60), ('point', 60), ('then switch', 60), ('to choose', 60), ('if it', 60), ('many', 59), ('out which', 59), ('green yellow', 59), ('appear', 58), ('tried', 58), ('results', 57), ('pay attention', 57), ('as you', 57), ('once you', 57), ('patterns', 56), ('and orange', 56), ('so you', 56), ('need', 55), ('attention to', 55), ('very', 54), ('didn', 54), ('as the', 54), ('you more', 54), ('the 5x', 54), ('basket the', 54), ('starts', 53), ('between the', 53), ('basket is', 53), ('down', 52), ('will give', 52), ('which gnome', 52), ('take you', 52), ('worth', 51), ('its', 51), ('gnomes and', 51), ('when it', 51), ('set', 50), ('though', 50), ('could', 50), ('figure', 50), ('need to', 50), ('work out', 50), ('yellow green', 50), ('the higher', 50), ('until the', 50), ('red purple', 50), ('might', 49), ('screen', 49), ('yield', 49), ('gnomes with', 49), ('other colour', 49), ('gnome and', 49), ('until you', 49), ('often', 48), ('those', 48), ('the amount', 48), ('the mushrooms', 48), ('you should', 48), ('blue green', 48), ('mushrooms and', 48), ('usually', 47), ('consistently', 47), ('every', 47), ('numbers', 47), ('the points', 47), ('to give', 47), ('is to', 47), ('stay', 46), ('goes', 46), ('test', 46), ('more than', 46), ('gnomes will', 46), ('select the', 46), ('focus', 45), ('given', 45), ('continue', 45), ('experiment', 45), ('note', 45), ('each round', 45), ('the first', 45), ('an', 44), ('during', 44), ('lower', 44), ('switching', 44), ('quick', 44), ('earn', 44), ('both', 44), ('opposite', 44), ('based on', 44), ('red pink', 44), ('figure out', 44), ('red or', 44), ('keys', 43), ('small', 43), ('the multiplier', 43), ('to pick', 43), ('pick the', 43), ('and pink', 43), ('give more', 43), ('before', 42), ('miss', 42), ('back', 42), ('way', 42), ('to keep', 42), ('it was', 42), ('to see', 42), ('it seems', 42), ('start to', 42), ('you see', 42), ('are two', 42), ('quickly', 41), ('help', 41), ('lead', 41), ('and red', 41), ('colours of', 41), ('go with', 41), ('of gnome', 41), ('the 1x', 41), ('gnome that', 41), ('mushrooms you', 41), ('most points', 41), ('strategy', 40), ('possible', 40), ('swap', 40), ('click', 40), ('one of', 40), ('to remember', 40), ('each gnome', 40), ('or yellow', 40), ('purple pink', 40), ('reward', 39), ('going', 39), ('does', 39), ('through', 39), ('sure you', 39), ('the next', 39), ('the brown', 39), ('for me', 39), ('the breaks', 39), ('the opposite', 39), ('lot', 38), ('about', 38), ('consistent', 38), ('got', 38), ('to work', 38), ('the blue', 38), ('it will', 38), ('which colour', 38), ('sure to', 38), ('green blue', 38), ('choice', 37), ('fingers', 37), ('long', 37), ('collect', 37), ('feel', 37), ('colours and', 37), ('stick to', 37), ('the screen', 37), ('give the', 37), ('the color', 37), ('scores', 36), ('another', 36), ('yields', 36), ('gnome is', 36), ('to do', 36), ('the space', 36), ('red brown', 36), ('is the', 36), ('taller', 35), ('where', 35), ('important', 35), ('linked', 35), ('to find', 35), ('purple brown', 35), ('this is', 35), ('the baskets', 35), ('you notice', 35), ('green gnomes', 35), ('to red', 35), ('appears', 34), ('generally', 34), ('provide', 34), ('values', 34), ('colored', 34), ('as it', 34), ('with that', 34), ('choosing the', 34), ('the tall', 34), ('brown gnomes', 34), ('other basket', 34), ('come', 33), ('key', 33), ('others', 33), ('their', 33), ('head', 33), ('bar', 33), ('the pattern', 33), ('get the', 33), ('the time', 33), ('to press', 33), ('many mushrooms', 33), ('out the', 33), ('space bar', 33), ('colour basket', 33), ('different coloured', 33), ('quite', 32), ('really', 32), ('re', 32), ('want', 32), ('and try', 32), ('during the', 32), ('better than', 32), ('mushrooms the', 32), ('the x5', 32), ('and stick', 32), ('from the', 32), ('have to', 32), ('giving you', 32), ('basket colour', 32), ('linked to', 32), ('orange blue', 32), ('etc', 31), ('into', 31), ('rewards', 31), ('size', 31), ('vs', 31), ('correspond', 31), ('decrease', 31), ('of points', 31), ('and you', 31), ('time to', 31), ('be the', 31), ('how many', 31), ('pink brown', 31), ('will get', 31), ('you pick', 31), ('get more', 31), ('that is', 31), ('press the', 31), ('your fingers', 31), ('look', 30), ('doing', 30), ('know', 30), ('even', 30), ('because', 30), ('best to', 30), ('colour gnome', 30), ('gnome gives', 30), ('the one', 30), ('think the', 30), ('that gnome', 30), ('until it', 30), ('gnomes give', 30), ('to make', 30), ('the pink', 30), ('brown purple', 30), ('selecting the', 30), ('the forest', 30), ('blue orange', 30), ('repeat', 29), ('choices', 29), ('worked', 29), ('started', 29), ('changed', 29), ('sets', 29), ('and it', 29), ('to try', 29), ('can change', 29), ('to select', 29), ('see which', 29), ('this game', 29), ('will take', 29), ('to yellow', 29), ('big', 28), ('randomly', 28), ('felt', 28), ('option', 28), ('paying', 28), ('will always', 28), ('you need', 28), ('the purple', 28), ('picking the', 28), ('note of', 28), ('want to', 28), ('colour and', 28), ('less mushrooms', 28), ('to switch', 28), ('gnomes the', 28), ('yellow blue', 28), ('the colors', 28), ('is giving', 28), ('to change', 28), ('color of', 28), ('other group', 28), ('scoring', 27), ('doesn', 27), ('shape', 27), ('result', 27), ('mind', 27), ('noticed', 27), ('to test', 27), ('the mushroom', 27), ('so if', 27), ('each time', 27), ('the short', 27), ('purple gnomes', 27), ('tried to', 27), ('the green', 27), ('mushrooms than', 27), ('will change', 27), ('the advice', 27), ('blue gnomes', 27), ('starts to', 27), ('hand', 26), ('bonus', 26), ('multipliers', 26), ('paired', 26), ('whether', 26), ('combinations', 26), ('off', 26), ('set of', 26), ('focus on', 26), ('different colours', 26), ('the start', 26), ('gave me', 26), ('game the', 26), ('5x multiplier', 26), ('worth more', 26), ('which one', 26), ('keep your', 26), ('to have', 26), ('the x1', 26), ('same colour', 26), ('pairs of', 26), ('gnome will', 26), ('correspond to', 26), ('pink red', 26), ('blue yellow', 26), ('play', 25), ('alternate', 25), ('follow', 25), ('smaller', 25), ('receive', 25), ('zero', 25), ('in each', 25), ('the keys', 25), ('do not', 25), ('each pair', 25), ('and keep', 25), ('with it', 25), ('points but', 25), ('try the', 25), ('as possible', 25), ('you don', 25), ('you re', 25), ('at all', 25), ('fingers on', 25), ('brown pink', 25), ('to one', 25), ('may be', 25), ('matter', 24), ('being', 24), ('picked', 24), ('specific', 24), ('avoid', 24), ('harvest', 24), ('begin', 24), ('chance', 24), ('identify', 24), ('end', 24), ('four', 24), ('ll', 24), ('amounts', 24), ('drop', 24), ('that will', 24), ('gives the', 24), ('the two', 24), ('go for', 24), ('other gnome', 24), ('chose the', 24), ('brown gnome', 24), ('points than', 24), ('other colours', 24), ('if there', 24), ('and see', 24), ('you choose', 24), ('basket if', 24), ('notice that', 24), ('mushrooms it', 24), ('with your', 24), ('but it', 24), ('see the', 24), ('for you', 24), ('gnome you', 24), ('or less', 24), ('red baskets', 24), ('baskets red', 24), ('two groups', 24), ('are different', 24), ('around', 23), ('gets', 23), ('turns', 23), ('together', 23), ('switched', 23), ('flat', 23), ('difference', 23), ('something', 23), ('determine', 23), ('particular', 23), ('this will', 23), ('that colour', 23), ('lot of', 23), ('to go', 23), ('you want', 23), ('gnome in', 23), ('but the', 23), ('the pair', 23), ('are the', 23), ('coloured gnome', 23), ('gnome on', 23), ('yellow gnomes', 23), ('in my', 23), ('lead to', 23), ('yellow or', 23), ('example if', 23), ('groups of', 23), ('hit', 22), ('yourself', 22), ('bit', 22), ('second', 22), ('believe', 22), ('trial', 22), ('dont', 22), ('focused', 22), ('previous', 22), ('fast', 22), ('seconds', 22), ('if they', 22), ('so try', 22), ('would be', 22), ('of colours', 22), ('if one', 22), ('not sure', 22), ('gnomes to', 22), ('to collect', 22), ('remember the', 22), ('that one', 22), ('at first', 22), ('yellow baskets', 22), ('is not', 22), ('points and', 22), ('you find', 22), ('colour gnomes', 22), ('orange gnomes', 22), ('gives more', 22), ('of basket', 22), ('fun', 21), ('say', 21), ('such', 21), ('longer', 21), ('sides', 21), ('half', 21), ('case', 21), ('selected', 21), ('within', 21), ('happens', 21), ('little', 21), ('associated', 21), ('now', 21), ('each colour', 21), ('is best', 21), ('it seemed', 21), ('found the', 21), ('remember which', 21), ('that are', 21), ('continue to', 21), ('gnome if', 21), ('swap to', 21), ('the taller', 21), ('then you', 21), ('such as', 21), ('think it', 21), ('can be', 21), ('remember to', 21), ('one gnome', 21), ('gnome the', 21), ('back to', 21), ('the end', 21), ('colored gnomes', 21), ('which gnomes', 21), ('purple red', 21), ('but this', 21), ('rounds to', 21), ('pink gnomes', 21), ('coloured basket', 21), ('which basket', 21), ('one forest', 21), ('pointy', 20), ('trying', 20), ('break', 20), ('overall', 20), ('options', 20), ('rule', 20), ('rules', 20), ('multiplier is', 20), ('my advice', 20), ('mushrooms so', 20), ('points you', 20), ('most of', 20), ('in your', 20), ('so that', 20), ('red blue', 20), ('side of', 20), ('see if', 20), ('appear in', 20), ('of which', 20), ('for while', 20), ('tall hats', 20), ('once the', 20), ('left or', 20), ('they are', 20), ('to figure', 20), ('game so', 20), ('change throughout', 20), ('find the', 20), ('certain colours', 20), ('you select', 20), ('or mushrooms', 20), ('hope', 19), ('still', 19), ('tended', 19), ('last', 19), ('collecting', 19), ('couldn', 19), ('maybe', 19), ('the round', 19), ('game is', 19), ('to which', 19), ('sometimes the', 19), ('pattern to', 19), ('gnomes were', 19), ('they will', 19), ('colours that', 19), ('which is', 19), ('one that', 19), ('don think', 19), ('it gives', 19), ('be quick', 19), ('blue gnome', 19), ('mushrooms then', 19), ('you start', 19), ('then the', 19), ('will start', 19), ('the different', 19), ('not to', 19), ('red gnomes', 19), ('tended to', 19), ('or right', 19), ('think that', 19), ('mushrooms in', 19), ('you may', 19), ('keep choosing', 19), ('mushrooms but', 19), ('so keep', 19), ('gnome for', 19), ('associated with', 19), ('to different', 19), ('one basket', 19), ('gnomes take', 19), ('easy', 18), ('move', 18), ('clicking', 18), ('ve', 18), ('shorter', 18), ('aim', 18), ('comes', 18), ('error', 18), ('track', 18), ('anything', 18), ('whenever', 18), ('rest', 18), ('likely', 18), ('collected', 18), ('correct', 18), ('shown', 18), ('split', 18), ('team', 18), ('to use', 18), ('to pay', 18), ('the rounds', 18), ('is better', 18), ('the value', 18), ('right side', 18), ('points the', 18), ('brown yellow', 18), ('there was', 18), ('gnomes always', 18), ('which side', 18), ('1x multiplier', 18), ('few rounds', 18), ('hat gnome', 18), ('the smaller', 18), ('in time', 18), ('basket until', 18), ('me the', 18), ('with red', 18), ('you ll', 18), ('there will', 18), ('to earn', 18), ('by the', 18), ('sets of', 18), ('lead you', 18), ('orange yellow', 18), ('gnomes which', 18), ('to start', 18), ('two different', 18), ('alternating', 17), ('instead', 17), ('below', 17), ('average', 17), ('following', 17), ('soon', 17), ('lots', 17), ('learn', 17), ('hard', 17), ('knomes', 17), ('bring', 17), ('large', 17), ('and remember', 17), ('come in', 17), ('so it', 17), ('of each', 17), ('help you', 17), ('group of', 17), ('gnomes each', 17), ('change so', 17), ('gnome to', 17), ('different colour', 17), ('which ones', 17), ('like the', 17), ('have fun', 17), ('earn more', 17), ('time and', 17), ('the ones', 17), ('of time', 17), ('over the', 17), ('not always', 17), ('out more', 17), ('the better', 17), ('that gives', 17), ('paired with', 17), ('while the', 17), ('yellow gnome', 17), ('in this', 17), ('this can', 17), ('is no', 17), ('green orange', 17), ('one colour', 17), ('important to', 17), ('down to', 17), ('other color', 17), ('one group', 17), ('are linked', 17), ('ensure', 16), ('least', 16), ('run', 16), ('count', 16), ('mostly', 16), ('check', 16), ('able', 16), ('type', 16), ('several', 16), ('completely', 16), ('pressing', 16), ('easier', 16), ('playing', 16), ('mental', 16), ('match', 16), ('personally', 16), ('using', 16), ('height', 16), ('changing', 16), ('provides', 16), ('eventually', 16), ('chosen', 16), ('earthy', 16), ('luck the', 16), ('but then', 16), ('the key', 16), ('trying to', 16), ('there seems', 16), ('think there', 16), ('next time', 16), ('are better', 16), ('round the', 16), ('left side', 16), ('of these', 16), ('mushrooms when', 16), ('able to', 16), ('time the', 16), ('than others', 16), ('after the', 16), ('as they', 16), ('track of', 16), ('one side', 16), ('up the', 16), ('left gnome', 16), ('all the', 16), ('basket for', 16), ('after while', 16), ('gnomes have', 16), ('or the', 16), ('which colours', 16), ('is on', 16), ('colour is', 16), ('the more', 16), ('through the', 16), ('that give', 16), ('and error', 16), ('always be', 16), ('gnomes in', 16), ('the numbers', 16), ('basket to', 16), ('colours red', 16), ('eye', 15), ('probably', 15), ('helps', 15), ('takes', 15), ('vary', 15), ('been', 15), ('working', 15), ('task', 15), ('thought', 15), ('beginning', 15), ('especially', 15), ('went', 15), ('successful', 15), ('am', 15), ('works', 15), ('tell', 15), ('fewer', 15), ('payout', 15), ('10', 15), ('have the', 15), ('change to', 15), ('two gnomes', 15), ('points for', 15), ('the second', 15), ('green gnome', 15), ('take note', 15), ('to it', 15), ('are worth', 15), ('to that', 15), ('keep track', 15), ('first round', 15), ('high number', 15), ('the beginning', 15), ('right gnome', 15), ('red gnome', 15), ('the previous', 15), ('mushrooms at', 15), ('mushrooms try', 15), ('with yellow', 15), ('keep selecting', 15), ('every time', 15), ('basket red', 15), ('will need', 15), ('the side', 15), ('it can', 15), ('purple gnome', 15), ('out for', 15), ('this happens', 15), ('the correct', 15), ('baskets the', 15), ('as this', 15), ('trial and', 15), ('brown red', 15), ('split into', 15), ('into two', 15), ('either red', 15), ('colour group', 15), ('order', 14), ('return', 14), ('things', 14), ('success', 14), ('rather', 14), ('decide', 14), ('decision', 14), ('row', 14), ('thing', 14), ('wasn', 14), ('selection', 14), ('cone', 14), ('combination', 14), ('received', 14), ('new', 14), ('show', 14), ('part', 14), ('increase', 14), ('category', 14), ('as well', 14), ('time it', 14), ('and be', 14), ('the coloured', 14), ('that was', 14), ('many points', 14), ('is good', 14), ('red orange', 14), ('for each', 14), ('time so', 14), ('however the', 14), ('higher amount', 14), ('one is', 14), ('lots of', 14), ('short hat', 14), ('short hats', 14), ('few times', 14), ('in row', 14), ('and if', 14), ('don miss', 14), ('result in', 14), ('not be', 14), ('was to', 14), ('orange green', 14), ('hand side', 14), ('color and', 14), ('time you', 14), ('tall brown', 14), ('gave more', 14), ('out on', 14), ('pink gnome', 14), ('gnome has', 14), ('advice is', 14), ('choose one', 14), ('out of', 14), ('game you', 14), ('baskets are', 14), ('you do', 14), ('which color', 14), ('at any', 14), ('it does', 14), ('your best', 14), ('basket colours', 14), ('numbers of', 14), ('better results', 14), ('to experiment', 14), ('go down', 14), ('basket will', 14), ('will provide', 14), ('the group', 14), ('is linked', 14), ('against', 13), ('maximise', 13), ('bigger', 13), ('advan

## DYNAMIC

In [94]:
topics_over_time = topic_model.topics_over_time(docs, classes)

topic_model.visualize_topics_over_time(topics_over_time)

10it [00:00, 39.12it/s]

In [35]:
topic_model.get_representative_docs(2)

["There's a pattern when it comes to the gnomes' colors. One of the colors in each color pairing (green/blue, pink/brown, red/yellow, orange/purple) will render more mushrooms and it is up to you figure out which color that is. Keep selecting the color you discovered yields more mushrooms. At certain points of the game, the color that gives you the most mushrooms may change, you will know when the color you have been selecting drops in mushrooms. When that happens, select the other color. If you are unsure if you should select the other color, experiment when it is x1, better to experiment then than when it's x5. While you want to make sure you pick the correct gnome, don't hesitate. It's better to select any gnome and possibly get mushrooms than not selecting one at all. Lastly, utilize those breaks. Even if you feel like you're on a streak, your brain is a muscle and giving it time to recover builds that muscle. Good luck!",
 "It might be difficult choosing the gnome that gives the most mushrooms. I did notice that at the beginning purple, brown, blue, and orange were giving me the most mushrooms. Once I noticed that these colors were giving me less, I started picking the other colors paired with them. So, red, yellow, pink, and green started giving me more mushrooms. It switches often, so if you're not sure, keep choosing any color until you notice which one gives you more and stick with that. So for example, I gave you the colors above to follow, but for you it could be different colors. Red, brown, pink, and orange may give you the most mushrooms at the same time while the others don't. So just choose the gnomes until you figure out which four are giving more mushrooms. Once you notice they are giving you less, pick the opposite colored gnomes and thy should give you more mushrooms.\xa0",
 'Pay close attention when a gnome gives you 0 mushrooms. This is likely a pattern to look out for, test this once or twice first to make sure it is not a trick. Sometimes different coloured gnomes can give more / give less mushrooms at random from my own observation. Usually, though, there is a pattern to be observed. After each break the coloured gnomes giving more or less mushrooms may switch up, meaning be prepared for a different sequence of gnomes that give either more or less mushrooms, or 0. It is important to choose the correct colour especially on 5x as it gives the most points! Best of luck :)']