## Import

In [189]:
from bertopic import BERTopic
import os
import pandas as pd
from sentence_transformers import SentenceTransformer
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer
import csv
from evaluation import evaluate_model
from bertopic.vectorizers import ClassTfidfTransformer

df = pd.read_csv(os.path.join(os.path.dirname(os.getcwd()), "data", "data_advice_fulltext.csv"))
docs = list(df["text"])
classes = list(df["gen"])

In [2]:
# Pre-calculate embeddings
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = embedding_model.encode(docs, show_progress_bar=True)

Batches: 100%|██████████| 32/32 [00:15<00:00,  2.05it/s]

In [249]:
#from sklearn.cluster import KMeans

run_name = "BERTopic_outlier_reduction_prob_005_nr_topics_15"

# Hyperparameters

n_neighbors = 30 # 15 -> BEST 30
n_components = 5 # 5 -> BEST 5
random_state = [0, 1, 37, 42, 73]
min_dist = 0.0
min_cluster_size = 10 # 10 -> BEST 10
min_df = 2 # 2 -> BEST 2 BUT 1 GOOD
ngram_range = (1, 2) # (1, 2) -> BEST (1, 2)
top_n_words = 10 # 10 -> BEST 10
#nr_topics = 15 # auto

# Data saving

data = []

# Setup different models

cluster_model = HDBSCAN(min_cluster_size=min_cluster_size, metric='euclidean', cluster_selection_method='eom', prediction_data=True)
#luster_model = KMeans(n_clusters=15)
vectorizer_model = CountVectorizer(stop_words="english", min_df=min_df, ngram_range=ngram_range)
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True) # enable by default --> BEST DEFAULT

# Train

for seed in random_state:
    umap_model = UMAP(n_neighbors=n_neighbors, n_components=n_components, min_dist=0.0, metric='cosine', random_state=seed)

    topic_model = BERTopic(

        # Pipeline models
        embedding_model=embedding_model,
        umap_model=umap_model,
        hdbscan_model=cluster_model,
        vectorizer_model=vectorizer_model,
        #ctfidf_model=ctfidf_model,

        # Hyperparameters
        top_n_words=top_n_words,
        n_gram_range=ngram_range,
        min_topic_size="auto", #use HDBSCAN
        verbose=True,
        #nr_topics = nr_topics, # base is auto

        # General parameters
        calculate_probabilities=True,
        language="english"
    )

    topics, probs = topic_model.fit_transform(docs, embeddings)
    
    # Outlier reduction
    new_topics = topic_model.reduce_outliers(docs, topics, probabilities=probs, strategy="probabilities", threshold=0)
    # new_topics = topic_model.reduce_outliers(docs, topics, strategy="embeddings")
    topic_model.update_topics(docs,
                              topics=new_topics,
                              vectorizer_model=vectorizer_model,
                              ctfidf_model=ctfidf_model
                              )

    # Evaluate model

    scores = evaluate_model(topic_model, docs, topk=topic_model.top_n_words)
    
    data.append([seed, scores[0], scores[1]])

df = pd.DataFrame(data, columns=["seed", "Diversity", "Coherence"])
df

2025-01-31 14:45:28,376 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-01-31 14:45:30,980 - BERTopic - Dimensionality - Completed ✓
2025-01-31 14:45:30,981 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-01-31 14:45:31,034 - BERTopic - Cluster - Completed ✓
2025-01-31 14:45:31,037 - BERTopic - Representation - Extracting topics from clusters using representation models.
2025-01-31 14:45:31,125 - BERTopic - Representation - Completed ✓
2025-01-31 14:45:31,235 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.
100%|██████████| 1/1 [00:00<00:00,  2.54it/s]
2025-01-31 14:45:33,924 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-01-31 14:45:36,207 - BERTopic - Dimensionality - Completed ✓
2025-01-31 14:45:36,208 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-01-31 14:45:36,256 - BERTopic - Cluster - Completed ✓
2025-01-31 14:45:36,259 - BERTopic - Representation - Extracting topics from clusters using representation models.
2025-01-31 14:45:36,324 - BERTopic - Representation - Completed ✓
2025-01-31 14:45:36,390 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.
100%|██████████| 1/1 [00:00<00:00,  2.69it/s]
2025-01-31 14:45:39,456 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-01-31 14:45:41,756 - BERTopic - Dimensionality - Completed ✓
2025-01-31 14:45:41,757 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-01-31 14:45:41,828 - BERTopic - Cluster - Completed ✓
2025-01-31 14:45:41,831 - BERTopic - Representation - Extracting topics from clusters using representation models.
2025-01-31 14:45:41,921 - BERTopic - Representation - Completed ✓
2025-01-31 14:45:41,990 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.
100%|██████████| 1/1 [00:00<00:00,  2.78it/s]
2025-01-31 14:45:44,834 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-01-31 14:45:47,159 - BERTopic - Dimensionality - Completed ✓
2025-01-31 14:45:47,159 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-01-31 14:45:47,207 - BERTopic - Cluster - Completed ✓
2025-01-31 14:45:47,209 - BERTopic - Representation - Extracting topics from clusters using representation models.
2025-01-31 14:45:47,275 - BERTopic - Representation - Completed ✓
2025-01-31 14:45:47,342 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.
100%|██████████| 1/1 [00:00<00:00,  2.77it/s]
2025-01-31 14:45:49,966 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-01-31 14:45:52,256 - BERTopic - Dimensionality - Completed ✓
2025-01-31 14:45:52,256 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-01-31 14:45:52,309 - BERTopic - Cluster - Completed ✓
2025-01-31 14:45:52,312 - BERTopic - Representation - Extracting topics from clusters using representation models.
2025-01-31 14:45:52,378 - BERTopic - Representation - Completed ✓
2025-01-31 14:45:52,447 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.
100%|██████████| 1/1 [00:00<00:00,  2.78it/s]

   seed  Diversity  Coherence
0     0   0.806250  -0.113407
1     1   0.823529  -0.076110
2    37   0.805882  -0.058474
3    42   0.817647  -0.058824
4    73   0.830000  -0.037813

Save model

In [165]:
embedding_model = "all-MiniLM-L6-v2"
topic_model.save(os.path.join(os.path.dirname(os.getcwd()), "results", "BERT_fine_tuning", run_name), serialization="safetensors", save_ctfidf=True, save_embedding_model=embedding_model)

Save data

In [166]:
param_str = str({
    "n_neighbors": n_neighbors,
    "n_components": n_components,
    "min_dist": min_dist,
    "random_state": random_state,
    "min_cluster_size": min_cluster_size,
    "min_df": min_df,
    "ngram_range": ngram_range,
    "top_n_words": top_n_words
})


data_run = [[run_name, param_str, df["Diversity"].mean(), df["Coherence"].mean()]]

df_run = pd.DataFrame(data_run, columns=["run_name", "params", "diversity", "coherence"])

df_run.to_csv(os.path.join(os.path.dirname(os.getcwd()), "results", "BERT_fine_tuning", "results.csv"), mode="a", header=False, index=False)

Show results

In [172]:
df_results = pd.read_csv(os.path.join(os.path.dirname(os.getcwd()), "results", "BERT_fine_tuning", "results.csv"))
df_results

,run_name,params,diversity,coherence
0,base,"{'n_neighbors': 15, 'n_components': 5, 'min_di...",0.518766,0.018410
1,UMAP_n_neighbors_20,"{'n_neighbors': 20, 'n_components': 5, 'min_di...",0.508158,0.015145
2,UMAP_n_neighbors_25,"{'n_neighbors': 25, 'n_components': 5, 'min_di...",0.539043,0.011082
3,UMAP_n_neighbors_30,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.543632,0.024256
4,UMAP_n_neighbors_35,"{'n_neighbors': 35, 'n_components': 5, 'min_di...",0.533987,0.014548
5,UMAP_n_neighbors_40,"{'n_neighbors': 40, 'n_components': 5, 'min_di...",0.529626,0.021350
6,UMAP_n_neighbors_45,"{'n_neighbors': 45, 'n_components': 5, 'min_di...",0.537632,0.020211
7,UMAP_n_neighbors_50,"{'n_neighbors': 50, 'n_components': 5, 'min_di...",0.520158,0.022319
8,UMAP_n_neighbors_55,"{'n_neighbors': 55, 'n_components': 5, 'min_di...",0.528634,0.025503
9,UMAP_n_neighbors_60,"{'n_neighbors': 60, 'n_components': 5, 'min_di...",0.532111,0.023156
10,UMAP_n_components_7,"{'n_neighbors': 15, 'n_components': 7, 'min_di...",0.509655,0.010337
11,UMAP_n_components_10,"{'n_neighbors': 15, 'n_components': 10, 'min_d...",0.511582,0.003970
12,UMAP_n_components_10_n_neighbors_30,"{'n_neighbors': 30, 'n_components': 10, 'min_d...",0.529322,0.016911
13,HDBSCAN_min_cluster_size_15,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.551054,0.016589
14,HDBSCAN_min_cluster_size_20,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.500000,0.025245
15,HDBSCAN_min_cluster_size_30,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.480667,0.017533
16,Vectorizer_ngram_range_13,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.536835,0.022609
17,Vectorizer_ngram_range_14,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.533595,0.021883
18,Vectorizer_min_df_10,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.452054,0.001002
19,Vectorizer_min_df_5,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.523978,0.016524
20,Vectorizer_min_df_1,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.525051,0.028604
21,c-tf-idf_bm25,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.587077,0.021597
22,c-tf-idf_bm25_rerun,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.580857,0.013207
23,c-tf-idf_reduce_frequent_words,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.876340,-0.052900
24,BERTopic_top_n_words_15,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.531833,-0.013220
25,BERTopic_top_n_words_20,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.535840,-0.040610
26,BERTopic_nr_topics_10,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.614000,0.041331
27,BERTopic_nr_topics_5,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.696000,0.046819
28,kmeans_n_clusters_20,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.444000,-0.000999
29,kmeans_n_clusters_10,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.496000,0.025894
30,kmeans_n_clusters_5,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.564000,0.003653
31,kmeans_n_clusters_7,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.508571,-0.000114
32,kmeans_n_clusters_15,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.501333,0.007884
33,BERTopic_outlier_reduction_prob_005,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.834454,-0.073890
34,BERTopic_outlier_reduction_prob_0_nr_topics_10,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.833333,0.020889
35,BERTopic_outlier_reduction_prob_0_nr_topics_5,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.905000,0.009967
36,BERTopic_outlier_reduction_prob_0_nr_topics_6,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.912000,0.049801
37,BERTopic_outlier_reduction_prob_0_nr_topics_7,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.912000,0.049801
38,BERTopic_outlier_reduction_prob_0_nr_topics_7,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.856667,0.025119
39,BERTopic_outlier_reduction_prob_0_nr_topics_8,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.865714,0.016466
40,BERTopic_outlier_reduction_prob_005_nr_topics_...,"{'n_neighbors': 15, 'n_components': 5, 'min_di...",0.910000,0.003041
41,BERTopic_outlier_reduction_prob_005_n_neigbhor...,"{'n_neighbors': 15, 'n_components': 5, 'min_di...",0.853419,-0.102670
42,BERTopic_outlier_reduction_prob_005,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.834454,-0.073890
43,BERTopic_outlier_reduction_prob_005_nr_topics_15,"{'n_neighbors': 30, 'n_components': 5, 'min_di...",0.845333,-0.060968

In [250]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,0,138,0_mushrooms_pair_number mushrooms_pattern,"[mushrooms, pair, number mushrooms, pattern, m...",[There's a pattern when it comes to the gnomes...
1,1,114,1_basket_yellow basket_red basket_baskets,"[basket, yellow basket, red basket, baskets, r...","[The blue, yellow and green gnomes show the ye..."
2,2,82,2_baskets_basket_basket colour_red basket,"[baskets, basket, basket colour, red basket, c...",[On the screen you will be presented with two ...
3,3,90,3_mushroom_colours mushrooms_colours_mushrooms,"[mushroom, colours mushrooms, colours, mushroo...",[You should try and test multiple colors to se...
4,4,66,4_scores_points_went_pink blue,"[scores, points, went, pink blue, pick, colors...",[there are similar colour patterns that come o...
5,5,54,5_points_earthy_group_points gnome,"[points, earthy, group, points gnome, gnomes p...",[Gnomes will provide points varying from 0-9 b...
6,6,34,6_hats_tall_hat_tall hats,"[hats, tall, hat, tall hats, hat tall, taller,...","[Do your best, seems pretty random and difficu..."
7,7,31,7_keys_fingers_hand_breaks,"[keys, fingers, hand, breaks, hands, focused, ...","[As each gnome appears, tap S for the left gno..."
8,8,26,8_forest_gnomes forest_forests_switch forest,"[forest, gnomes forest, forests, switch forest...","[There are two forests. Green, orange, yellow,..."
9,9,28,9_knomes_earners_knome_purple blue,"[knomes, earners, knome, purple blue, brown us...","[try to choose blue, green and yellow. Avoid b..."
10,10,26,10_pattern_random_50_pattern game,"[pattern, random, 50, pattern game, random pat...","[I found no discernable pattern, it was almost..."
11,11,23,11_modifier_hat_gnomes tall_gnomes longer,"[modifier, hat, gnomes tall, gnomes longer, ha...",[I found that the gnome with the tall hat give...
12,12,21,12_groups_scores_score_higher scores,"[groups, scores, score, higher scores, groups ...","[The gnomes wearing green, blue, orange and ye..."
13,13,60,13_hold_reward_better_screen,"[hold, reward, better, screen, gnomes better, ...",[pay attention to the colour of the gnomes and...
14,14,22,14_cone_hat_shaped_cone shaped,"[cone, hat, shaped, cone shaped, gnome short, ...",[I found that when you had two gnomes with a c...
15,15,27,15_taller_taller gnomes_tall_taller gnome,"[taller, taller gnomes, tall, taller gnome, sh...",[I found the shorter gnomes gave better reward...
16,16,38,16_value_value gnomes_yellow gnome_high,"[value, value gnomes, yellow gnome, high, red ...",[There are several pairs of gnomes that appear...
17,17,45,17_multiplier_paying_5x_1x,"[multiplier, paying, 5x, 1x, paired gnome, use...",[Keep an eye on the colour of the gnomes throu...
18,18,27,18_hat_hats_small hat_pointy,"[hat, hats, small hat, pointy, little, worth, ...",[Pink is worth more than blue. Orange tends to...
19,19,48,19_basket_red basket_yellow basket_colour group,"[basket, red basket, yellow basket, colour gro...","[I think to get a high score, match the colour..."

In [251]:
topic_model.visualize_hierarchy(top_n_topics=50)

In [252]:
topic_model.visualize_documents(docs)

## DYNAMIC

In [253]:
topics_over_time = topic_model.topics_over_time(docs, classes)

topic_model.visualize_topics_over_time(topics_over_time)

0it [00:00, ?it/s]

10it [00:00, 14.41it/s]

In [260]:
a = topic_model.probabilities_
b = topic_model.get_document_info(docs)